### ISSUE TITLE
Question regarding cell type information

### ISSUE THREAD

**Issue by Shawnmhy** [labsyspharm/CRC_atlas_2022#1]
Hi team, I have download the spatial feature table provided here: [https://github.com/labsyspharm/CRC_atlas_2022/blob/main/README.md#crc1-images](url)

However, the cell phenotype seems missing from this table. Could you please suggest how to retrieve the cell type info?

Thank you in advance!

**Comment by jrlin1001** [comment]
Hi Shawnmhy,

Sorry for the confusion.  In this study, we didn't explicitly define "cell types" as others, rather just use gated markers throughout.  However, I just uploaded a example data table from CRC1-097:

https://github.com/labsyspharm/CRC_atlas_2022/tree/main/data_example_CRC1_097

You can find the cell type label at column 69.   Hope this helps.  

Best,
-jerry-

**Comment by Shawnmhy** [comment]
Hi Jerry, thank you so much for your quick response! I am also wondering, what is the unit of the AREA and coordinates in the table? If it is in pixel, what is the pixel size? Also, is it possible that you can provide the complete table (with the cell type label) for all samples?

**Comment by jrlin1001** [comment]
Hi Shawnmhy,  the unit of the area and coordinates are in micron (um).  happy to share the complete table.  However, it would be challenging to share through Github.   Please contact me through email: jia-ren_lin(at)hms.harvard.edu

**Comment by Shawnmhy** [comment]
Thank you Jerry, email sent.
