### ISSUE TITLE
Are .ome.tif images greyscale?

### ISSUE THREAD

**Issue by ozkilim** [labsyspharm/CRC_atlas_2022#2]
Thank you so much for this work!

I have downloaded a HandE image and when loading the .ome.tif I see it is greyscale not RGB. I have tried various loading strategies but all give me back greyscale data. 

Have you had any experience with this? Or seen this issue?

Best,
Oz

**Comment by jrlin1001** [comment]
It's a 3-channel grayscale ome tiff image, which contains R/G/B images in each channels.   If you load it with any bio-formats compatible software/package (eg. ImageJ), you should be able to covert it back to color images.

**Comment by ozkilim** [comment]
Thank you for your quick response. I have tried loading it with multiple bio-format compatible software packages (open slide, tifffslide etc) and I find that all the 3 channels are duplicates. Do you think I am doing something incorrect still?

**Comment by jrlin1001** [comment]
The R/G/B channels should look very "similar", but not exactly the same.   Could you define/describe why you think these are "duplicates"?

**Comment by jrlin1001** [comment]
![image](https://github.com/labsyspharm/CRC_atlas_2022/assets/7151792/fd23fdda-0a7a-4dbf-91b6-1b6dafe5279e)
Here is from one of the images (CRC01-#006), RGB composite and R/G/B

**Comment by ozkilim** [comment]
Ok. I think it is likely as issue on my side I just cannot figure out what is going on.  I download an image and run:

```
from openslide import OpenSlide
import numpy as np

slide = OpenSlide('./WD-76845-001.ome.tif')
level = 0
image = np.array(slide.read_region((0, 0), level, slide.level_dimensions[level]))
```

I get: 

image.shape = (54325, 57346, 4)

Then when I run:

`image[:,:,0].all() == image[:,:,1].all() == image[:,:,2].all()`

I get **True** supposedly meaning all channels are duplicates. 

Do you have any ideas on what I could be doing wrong? When I run this same script for other WSIs I get **False** when comparing the channels.

Best,
Oz

**Comment by Yu-AnChen** [comment]
Hi @ozkilim, as of now [openslide does not support tiled pyramidal ome-tiff](https://github.com/openslide/openslide/pull/344). I'd recommend using `tifffile` + `zarr`. 

Here's the example script I'd use

```python
%%time
import numpy as np
import tifffile
import zarr

zimg = zarr.open(
    tifffile.imread("WD-76845-001.ome.tif", aszarr=True),
    mode="r",
)

print(
f'''
"zarr group"
{zimg.info}

"level 0"
{zimg[0].info}

"level 1"
{zimg[1].info}

Is pixel data equal: {np.all(zimg[0][0, :1000, :1000] == zimg[0][1, :1000, :1000])}
'''
)
```

And the outputs

```txt
"zarr group"
Name        : /
Type        : zarr.hierarchy.Group
Read-only   : True
Store type  : zarr.storage.KVStore
No. members : 7
No. arrays  : 7
No. groups  : 0
Arrays      : 0, 1, 2, 3, 4, 5, 6


"level 0"
Name               : /0
Type               : zarr.core.Array
Data type          : uint8
Shape              : (3, 54325, 57346)
Chunk shape        : (1, 1024, 1024)
Order              : C
Read-only          : True
Compressor         : None
Store type         : zarr.storage.KVStore
No. bytes          : 9345964350 (8.7G)
No. bytes stored   : 235
Storage ratio      : 39770061.1
Chunks initialized : 0/9234


"level 1"
Name               : /1
Type               : zarr.core.Array
Data type          : uint8
Shape              : (3, 27163, 28673)
Chunk shape        : (1, 1024, 1024)
Order              : C
Read-only          : True
Compressor         : None
Store type         : zarr.storage.KVStore
No. bytes          : 2336534097 (2.2G)
No. bytes stored   : 237
Storage ratio      : 9858793.7
Chunks initialized : 0/2349


Is pixel data equal: False

CPU times: total: 312 ms
Wall time: 328 ms
```

**Comment by ozkilim** [comment]
I spoke with Jeremy Muhlich over email and it seems the data can be converted with https://github.com/labsyspharm/ome-tiff-pyramid-tools/blob/master/rgb_merge.py 

Thanks so much for the help!

**Comment by Yu-AnChen** [comment]
Great! Closing this now.
