### ISSUE TITLE
Scalefactor for Cell positions in spatial-features.csv from microns to pixel

### ISSUE THREAD

**Issue by mjheid** [labsyspharm/CRC_atlas_2022#4]
Hi,

As mentioned [here](https://github.com/labsyspharm/CRC_atlas_2022/issues/1#issuecomment-1644992241):

> ...the unit of the area and coordinates are in micron (um).  ...

for the spatial features table. I am currently trying to validate a model which makes predictions for cells based on Image data and cell positions. For that I would need to know the positions of cells in pixels(or do cell segmentation on my own). 

What is the scalefactor for microns to pixels(should be something around 35 ish)? I did try to find this information elsewhere as well, but have not found it in this github, the associated paper, or from the manufacturer of the named instrument (20x objective (0.75 NA) on a CyteFinder slide scanning fluorescence microscope (RareCyte Inc. Seattle WA)).

Appreciate the help!

**Comment by jrlin1001** [comment]
Hi mjheid,   for the dataset you have, we imaged at 20x with 2x2 binning, so it should be 0.65 um per pixel.

**Comment by mjheid** [comment]
Thank you for the fast answer!

Either I am doing something significantly wrong or this scalefactor is not accurate...
I tested this scalefactor (0.65 * coord value)for image CRC06 on image channel 0, and colored cell points by the measured area. Points in the image get plotted in the top left corner:
![crc06-points065](https://github.com/labsyspharm/CRC_atlas_2022/assets/99927636/a50a123d-a9a2-47ff-becf-c92a443d9555)
If we zoom in on the top left corner we get a more obvious view:
![crc06-zoom065](https://github.com/labsyspharm/CRC_atlas_2022/assets/99927636/4b794cfb-cba4-4e16-8031-f024ca85916f)
If I scale coordinates with a factor of 35 I get somewhat more accurate cell positions:
![crc06-scale35](https://github.com/labsyspharm/CRC_atlas_2022/assets/99927636/833b041d-fddf-4bbf-a8c8-76264401a488)

This is the code I used to produce these plots, in case that is needed/helps:
```
from skimage import io
import numpy as np
import pandas as pd
import squidpy as sq
import scanpy as sc
from anndata import AnnData
import matplotlib.pyplot as plt

#read image
img = io.imread('path/to/CRC06.ome.tif', plugin='tifffile')
img = np.transpose(img, (1,2,0))    #swap channel axis for image plotting later

#get x and y coords
df = pd.read_csv('path/to/CRC06.csv')
coords = pd.DataFrame()
sf = 0.65   #or 35
coords['x'] = df['X'] * sf
coords['y'] = df['Y'] * sf
coordinates = np.column_stack((coords["x"].to_numpy(), coords["y"].to_numpy()))

#create adata object to plot image with cell locations
counts = np.random.default_rng(42).integers(0, 15, size=(df.shape[0], 1))   #needed for the data obj, we disregard this
adata = AnnData(counts, obsm={"spatial": coordinates})
spatial_key = "spatial"
library_id = "tissue42"
adata.uns[spatial_key] = {library_id: {}}
adata.uns[spatial_key][library_id]["images"] = {}
adata.uns[spatial_key][library_id]["images"] = {"hires": img}
adata.uns[spatial_key][library_id]["scalefactors"] = {"tissue_hires_scalef": 1, "spot_diameter_fullres": 1,}

#add area values to adata
adata.obs['area'] = df['AREA'].values

#plot image
sq.pl.spatial_scatter(adata, color='area', size=100, img_channel=0)
plt.show()
```
Do I have some misunderstanding on how the scaling works?

Thank you for your help!

**Comment by jrlin1001** [comment]
Not sure I got you correctly, but you need to divide the coordinates we provided with 0.65 to obtain the pixel values, not the other way around.

**Comment by mjheid** [comment]
That was a dumb mistake from my side, my bad.

Still, this results in a scale factor of 1/0.65=1.53846153846 which should still be too small. While larger then the scale factor of 0.65 plotted above, it is still significant smaller then the scale factor of 35(plotted above as well) which also does not seem to cover the whole Image. I can provide a plot for the scale factor 1/0.65 tomorrow if needed. 

Are cell coordinates only for a segment of the image? Am I missing something else?

Thank you so much for your help, I hope I am not too much of a bother

**Comment by jrlin1001** [comment]
Hi mjheid, sorry I might misread your question/problem.  After seeing your code, I believe you might only open a different layer of pyramid.   You will need to specify the layer/level you want to read here (should be the level 1), something like this "second_level = imread('temp.ome.tif', series=0, level=1)".

**Comment by mjheid** [comment]
Hi jrlin1001, thank you for your help, I was not aware of the different viewing levels, sorry for wasting time on that.
Do these Cell Positions for the Main CyCIF panel for CRC06  level 4 look correct?

![crc06-level4](https://github.com/labsyspharm/CRC_atlas_2022/assets/99927636/e2d54eb6-fbe6-4492-96eb-563bf70365bf)

Cell Positions still seem not to match positions on the image.
Here some information on the dimensions of the different image levels and the max values for X and Y positions:
```
>>> df['X'].max()
842.785
>>> df['Y'].max()
677.696
>>> (1/0.65)*df['X'].max()
1296.5923076923075
>>> (1/0.65)*df['Y'].max()
1042.6092307692306
>>> io.imread('data/raw/CRC/CRC06.ome.tif', plugin='tifffile', series=0, level=5).shape
(36, 783, 974)
>>> io.imread('data/raw/CRC/CRC06.ome.tif', plugin='tifffile', series=0, level=4).shape
(36, 1566, 1947)
>>> io.imread('data/raw/CRC/CRC06.ome.tif', plugin='tifffile', series=0, level=3).shape
(36, 3132, 3893)
>>> io.imread('data/raw/CRC/CRC06.ome.tif', plugin='tifffile', series=0, level=2).shape
(36, 6263, 7785)
>>> io.imread('data/raw/CRC/CRC06.ome.tif', plugin='tifffile', series=0, level=1).shape
(36, 12526, 15569)
>>> io.imread('data/raw/CRC/CRC06.ome.tif', plugin='tifffile', series=0, level=0).shape
(36, 25051, 31137)
```
When looking at the dimensions of the images and the max values for X and Y, only level 4 and 5 seem to be reasonable to have identified Cells on the whole Image... But level 4 and scaled coordinates do not cover the whole Image. Level 5 without scaling the Cell positions appears to be the closest fit for the whole Image(when scaling Cell positions some Cell positions appear outside of the Image: max scaled X of 1296.4 > level 5 Image dim ), but does not cover the whole Image as well:
![crc06-level5](https://github.com/labsyspharm/CRC_atlas_2022/assets/99927636/af7e053a-3059-4503-8492-535a3885fa07)

Relevant changed code to produce:
```
img = io.imread('path/to/CRC06.ome.tif', plugin='tifffile', series=0, level=4) 
img = np.transpose(img, (1,2,0))    #swap channel axis for image plotting later

#get x and y coords
df = pd.read_csv('path/to/CRC06.csv')
coords = pd.DataFrame()
sf = 0.65   #or 35
coords['x'] = df['X'] / sf
coords['y'] = df['Y'] / sf
```
To be clear, my issue is that I want to be sure that I have the correct Cell centroid coordinates in pixel values. I might be missing something else that is obvious? I tried swapping x and y in case I made a mistake there, but that still results in not covering the whole image... I will take another look at the ome.tiff file docs in hope I find something.

Thank you for your help

**Comment by jrlin1001** [comment]
Hi mjheid, all the quantification was done with lowest level images (herein level 0).   Also, after checking your code again, I realized you might use the wrong coordinates.   The segmentation and quantification were done frame-by-frame, then we assembled it back to the full image.  The (X,Y) coordinates are only in the local frames, while the (Xt,Yt) are the global coordinates.   In the CRC06 table, the maximum numbers of (Xt,Yt) are (19888um,16281um), which should be similar to the image size (31137,25051) * 0.65 = (20239um, 16283um), despite some empty spaces without cells

**Comment by mjheid** [comment]
Ok awesome, this fixed everything!
I think I initially looked at the first few X,Y and Xt,Yt coordinates, which were equal, choose the wrong one and then forgot about it completely without further checking...
Updated code that works:
```
img = io.imread('path/to/CRC06.ome.tif', plugin='tifffile', series=0, level=0) 
img = np.transpose(img, (1,2,0))    #swap channel axis for image plotting later

#get x and y coords
df = pd.read_csv('path/to/CRC06.csv')
coords = pd.DataFrame()
sf = 0.65   #or 35
coords['x'] = df['Xt'] / sf
coords['y'] = df['Yt'] / sf
```

Thank you for your help and time!
