### ISSUE TITLE
Inquiry about Free Access to CRC Atlas Data

### ISSUE THREAD

**Issue by csybdwbs** [labsyspharm/CRC_atlas_2022#5]
Hello,

Thank you for providing the CRC Atlas dataset for research purposes. I am currently interested in utilizing this dataset for my research on [briefly mention your research purpose, e.g., colorectal cancer analysis]. However, I noticed that the S3 bucket is configured for "Requester Pays," and the estimated download cost is quite high for my research budget.

Could you please let me know if:
1. There are any alternative ways to access this dataset without the high download cost?
2. It might be possible to obtain a smaller subset of the data to reduce the fees?

Thank you very much for your assistance and for making this valuable resource available to the community.

Best regards,  
Shangyan

**Comment by Yu-AnChen** [comment]
Hi I have confirmed that the requester pays is disabled for this bucket `s3://lin-2021-crc-atlas/` and the data is publicly available. If that's not the case, please let us know which file you are trying to access.

**Comment by csybdwbs** [comment]
ok，I‘will try again. Thank you！
